### PR TITLE
Fix/formatter indentation

### LINKED ISSUE #619: Formatter indentation issues
There are some cases where the formatter doesn't indent multi-line statements.
I think the following cover most of the unexpected behaviors I've encountered

* functions with arguments broken over multiple lines, like
```d
void foo(
string a, 
string b
) {}
``` 
* array literals spanning multiple lines
```d
int[] a = [
1,
2,
3,
];
```

* function calls spanning multiple lines

```d
void foo() {
    bar(1,
    2);    
}
```

* chains of function calls

```d
abc.filter!(...)
.map!(...)
.array;
```

### PR DESCRIPTION
**Pull request by etienne02**
Better to review by commits (first one, converts java to kotlin)
Closes #619

### CODE REVIEW

File: src/main/kotlin/io/github/intellij/dlanguage/features/DCommenter.kt [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+        return "/*"
+    }
+
+    override fun getBlockCommentSuffix(): String {
+        return "*/"
+    }
+
+    override fun getCommentedBlockCommentPrefix(): String? {
+        return null
+    }
```
Comment (SingingBush) [inline src/main/kotlin/io/github/intellij/dlanguage/features/DCommenter.kt:23]: a convenience with Kotlin is that these getters can be shortened to a single line. eg:

```
override fun getBlockCommentSuffix(): String = "*/"
```

**Review by SingingBush — APPROVED** [review]
