### PR TITLE
Fix(#1125): Reduce the parser recursion stack when parsing comma exp

### LINKED ISSUE #1055: StackOverflowError in DLangParser for v1.36.3
**Desktop (please provide environment info):**
 - IDE: Intellij CE 2024.3.4.1
 - Plugin Version 1.36.3

Sentry error `6cc8ff14224a46e18366a0c079b7fb55`

```
java.lang.StackOverflowError: null
    at it.unimi.dsi.fastutil.ints.IntArrayList.add(IntArrayList.java:323)
    at com.intellij.lang.impl.MarkerProduction.addDone(MarkerProduction.java:113)
    at com.intellij.lang.impl.PsiBuilderImpl.processDone(PsiBuilderImpl.java:916)
    at com.intellij.lang.impl.PsiBuilderImpl.access$900(PsiBuilderImpl.java:49)
    at com.intellij.lang.impl.PsiBuilderImpl$StartMarker.done(PsiBuilderImpl.java:378)
    at io.github.intellij.dlanguage.parser.DLangParser.parsePrimaryExpression(DLangParser.kt:5411)
    at io.github.intellij.dlanguage.parser.DLangParser.parsePostfixExpression_terminal(DLangParser.kt:7593)
    at io.github.intellij.dlanguage.parser.DLangParser.parsePostfixExpression(DLangParser.kt:7690)
    at io.github.intellij.dlanguage.parser.DLangParser.parsePowExpression(DLangParser.kt:5247)
    at io.github.intellij.dlanguage.parser.DLangParser.parseUnaryExpression(DLangParser.kt:7589)
    at io.github.intellij.dlanguage.parser.DLangParser.parseMulExpression(DLangParser.kt:4682)
    at io.github.intellij.dlanguage.parser.DLangParser.parseAddExpression(DLangParser.kt:26)
    at io.github.intellij.dlanguage.parser.DLangParser.parseShiftExpression(DLangParser.kt:5782)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCmpExpression(DLangParser.kt:1860)
    at io.github.intellij.dlanguage.parser.DLangParser.parseAndExpression(DLangParser.kt:315)
    at io.github.intellij.dlanguage.parser.DLangParser.parseXorExpression(DLangParser.kt:7990)
    at io.github.intellij.dlanguage.parser.DLangParser.parseOrExpression(DLangParser.kt:4860)
    at io.github.intellij.dlanguage.parser.DLangParser.parseAndAndExpression(DLangParser.kt:292)
    at io.github.intellij.dlanguage.parser.DLangParser.parseOrOrExpression(DLangParser.kt:4883)
    at io.github.intellij.dlanguage.parser.DLangParser.parseTernaryExpression(DLangParser.kt:7069)
    at io.github.intellij.dlanguage.parser.DLangParser.parseAssignExpression(DLangParser.kt:1196)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2873)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2878)
```

### LINKED ISSUE #1125: stack overflow in DLangParser parseCommaExpression
encountered this issue while importing a new project on Windows with 1.37.3:

```
Error while indexing C:\D\dmd2\src\phobos\std\internal\unicode_comp.d
To reindex this file IDE has to be restarted

java.lang.StackOverflowError
	at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:42)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner$Indexer.getApplierForFileIndexUpdate(IndexUpdateRunner.kt:347)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner$Indexer.indexOneFile(IndexUpdateRunner.kt:299)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.indexOneFileHandleExceptions(IndexUpdateRunner.kt:239)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner$doIndexFiles$1$1.invokeSuspend(IndexUpdateRunner.kt:149)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner$processFileSetInParallel$2$1$1$1$invokeSuspend$$inlined$useWithScope$default$1.invokeSuspend(IndexUpdateRunner.kt:59)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner$processFileSetInParallel$2$1$1$1.invokeSuspend(IndexUpdateRunner.kt:563)
Caused by: java.lang.StackOverflowError
	at java.base/java.util.HashMap.hash(HashMap.java:338)
	at java.base/java.util.HashMap.getNode(HashMap.java:576)
	at java.base/java.util.HashMap.containsKey(HashMap.java:602)
	at java.base/java.util.HashSet.contains(HashSet.java:213)
	at io.github.intellij.dlanguage.parser.DLangParser.isLiteral(DLangParser.kt:5559)
	at io.github.intellij.dlanguage.parser.DLangParser.parsePrimaryExpression(DLangParser.kt:5387)
	at io.github.intellij.dlanguage.parser.DLangParser.parsePostfixExpression_terminal(DLangParser.kt:7598)
	at io.github.intellij.dlanguage.parser.DLangParser.parsePostfixExpression(DLangParser.kt:7695)
	at io.github.intellij.dlanguage.parser.DLangParser.parsePowExpression(DLangParser.kt:5232)
	at io.github.intellij.dlanguage.parser.DLangParser.parseUnaryExpression(DLangParser.kt:7594)
	at io.github.intellij.dlanguage.parser.DLangParser.parseMulExpression(DLangParser.kt:4667)
	at io.github.intellij.dlanguage.parser.DLangParser.parseAddExpression(DLangParser.kt:26)
	at io.github.intellij.dlanguage.parser.DLangParser.parseShiftExpression(DLangParser.kt:5767)
	at io.github.intellij.dlanguage.parser.DLangParser.parseCmpExpression(DLangParser.kt:1843)
	at io.github.intellij.dlanguage.parser.DLangParser.parseAndExpression(DLangParser.kt:315)
	at io.github.intellij.dlanguage.parser.DLangParser.parseXorExpression(DLangParser.kt:8006)
	at io.github.intellij.dlanguage.parser.DLangParser.parseOrExpression(DLangParser.kt:4845)
	at io.github.intellij.dlanguage.parser.DLangParser.parseAndAndExpression(DLangParser.kt:292)
	at io.github.intellij.dlanguage.parser.DLangParser.parseOrOrExpression(DLangParser.kt:4868)
	at io.github.intellij.dlanguage.parser.DLangParser.parseTernaryExpression(DLangParser.kt:7043)
	at io.github.intellij.dlanguage.parser.DLangParser.parseAssignExpression(DLangParser.kt:1196)
	at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2859)
	at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2864)
	at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2864)
	at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2864)
	at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2864)
	at io.github.intellij.dlanguage.parser.DLangParser.parseCommaExpression(DLangParser.kt:2864)

```

### PR DESCRIPTION
**Pull request by etienne02**
Should closes #1125 
Should also closes #1055 

I’m not able to verify it as my computer has a big enough stack to not trigger the overflow, but the while loop should remove the stack growth. That’s also why I didn’t added a test for it.

Majority of changes are just cleaning.

### CODE REVIEW

File: dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/parser/DLangParser.kt [hunk 1]
```diff
@@ -2856,18 +2856,17 @@ internal class DLangParser(private val builder: PsiBuilder) {
      * ;)
      */
     fun parseCommaExpression(): PsiBuilder.Marker? {
-        val assign = parseAssignExpression() ?: return null
-        if (currentIs(DlangTypes.OP_COMMA)) {
-            val m = assign.precede()
+        var assign = parseAssignExpression() ?: return null
```
Comment (etienne02) [inline dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/parser/DLangParser.kt:2859]: Actual fix, replacement of recursion with a while loop
