### PR TITLE
Fix 1104/fix tests with intellij 2025.2

### LINKED ISSUE #1104: support Intellij 2025.2
2025.2 is out now

### PR DESCRIPTION
**Pull request by etienne02**
closes #1104

### CODE REVIEW

File: sdlang/src/main/kotlin/io/github/intellij/dlanguage/sdlang/SDLangFileType.kt [hunk 1]
```diff
@@ -8,5 +8,5 @@ object SDLangFileType : LanguageFileType(SimpleDefinitionLanguage) {
     override fun getName(): String = "SDLang"
     override fun getDefaultExtension(): String = "sdl"
     override fun getDescription(): String = "Simple Definition Language"
-    override fun getIcon(): Icon = PlainTextFileType.INSTANCE.icon
+    override fun getIcon(): Icon = PlainTextFileType.INSTANCE.icon!!
```
Comment (etienne02) [inline sdlang/src/main/kotlin/io/github/intellij/dlanguage/sdlang/SDLangFileType.kt:11]: The actual fix

**Review by SingingBush — APPROVED** [review]
