### PR TITLE
Fix 1039/fully recognize token string lexing

### LINKED ISSUE #1039: q strings do not support braces in string
**Desktop (please provide environment info):**
 - OS: Windows 10
 - IDE: IntelliJ IDEA 2024.2.5
 - Plugin Version: 1.36.1

**Describe the problem**

When have a ``q{}`` string, which contains a ``""`` string, that has a unmatched ``{``  in it, the parser will fail.

**Please provide full details to reproduce the problem**

``q{".-,.-`{-.c-u"}``

**Screenshots**

Line 77 has the ``{`` that's within a ``"`` string.

Capture

### PR DESCRIPTION
**Pull request by etienne02**
Closes #1039 

It also colorize the token string like others strings.

A future improvements would be to integrate with intelliLang in order to colorize the token string contents properly

### CODE REVIEW

File: src/test/kotlin/io/github/intellij/dlanguage/lexer/DlangLexerTest.kt [hunk 1]
```diff
@@ -193,7 +193,6 @@ BAD_CHARACTER ('q"/test"d;')
     fun testtokens_unordered_le()         = doTest()
     fun testtokens_xor()                  = doTest()
     fun testtokens_xor_assign()           = doTest()
-    fun testtokenstrings()                = doTest()
```
Comment (etienne02) [inline src/test/kotlin/io/github/intellij/dlanguage/lexer/DlangLexerTest.kt:196]: This test was redundant with the other

File: src/test/resources/gold/lexer/expected/string_tokens.txt [hunk 2]
```diff
@@ -38,11 +38,7 @@ DlangTokenType.ID ('c')
 WHITE_SPACE (' ')
 DlangTokenType.= ('=')
 WHITE_SPACE (' ')
-DlangTokenType.TOKEN_STRING ('q{/*}')
-DlangTokenType.* ('*')
-DlangTokenType./ ('/')
-WHITE_SPACE (' ')
-DlangTokenType.} ('}')
+DlangTokenType.TOKEN_STRING ('q{/*}*/ }')
```
Comment (etienne02) [inline src/test/resources/gold/lexer/expected/string_tokens.txt:41]: :smile:

File: src/main/kotlin/io/github/intellij/dlanguage/lexer/DHighlightingLexer.kt [hunk 3]
```diff
@@ -1,14 +1,12 @@
...
-import com.intellij.lexer.FlexAdapter
 import com.intellij.lexer.LayeredLexer
-import io.github.intellij.dlanguage.DlangLexer
 import io.github.intellij.dlanguage.psi.DlangTypes.*
 
 /**
  * Second step highlight pass to handle errors in tokens (string contents for example)
  */
-class DHighlightingLexer : LayeredLexer(FlexAdapter(DlangLexer())) {
+class DHighlightingLexer : LayeredLexer(DlangLexer()) {
```
Comment (SingingBush) [inline src/main/kotlin/io/github/intellij/dlanguage/lexer/DHighlightingLexer.kt:9]: is the new DlangLexer an implementation of FlexAdapter

Comment (etienne02) [reply src/main/kotlin/io/github/intellij/dlanguage/lexer/DHighlightingLexer.kt:9]: No, it’s a simple `LexerBase` but uses the generated Lexer (with jflex) internally. `LexerAdapter` is an adapter for JFlex lexer to a `LexerBase` (Jetbrain interface).
